version: '2.1'
orbs:
  docker: circleci/docker@2.4.0
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: buildspace/storage-api
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: buildspace/storage-api
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          # use-remote-docker: true