version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
  docker: circleci/docker@1.5.0
jobs:
  build:
    docker:
      - image: cimg/base:current
        resource_class: project-buildspace/circleci
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Renew swagger
          command: swag init
          
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t buildspace/storage-api:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push buildspace/storage-api:$TAG