version: '2.1'
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build-push:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker

      - docker/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME

      - docker/build:
          image: buildspace/storage-api
          
      - docker/push:
          image: buildspace/storage-api

workflows:
  build-push-docker-image:
    jobs:
      - build-push