version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
  docker: circleci/docker@1.5.0
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: buildspace/storage-api
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD1
jobs:
  publishLatestToHub: 
        executor: docker-publisher
  # build:
  #   docker:
  #     - image: cimg/base:current
  #       auth:
  #         username: $DOCKER_USERNAME
  #         password: $DOCKER_PASSWORD
    resource_class: project-buildspace/circleci
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Renew swagger
          command: swag init
          
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t buildspace/storage-api:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push buildspace/storage-api:$TAG