version: '2.1'
orbs:
  docker: circleci/docker@2.4.0
jobs:
  docker-login:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Docker ps
          command: docker ps -a

      - run:
          name: Docker login
          command: echo DOCKER_PASSWORD | docker login --username DOCKER_USERNAME --password-stdin

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: buildspace/storage-api
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker-login
      - docker/publish:
          image: buildspace/storage-api
          # remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          # use-remote-docker: true